kind: pipeline
type: docker
name: default

steps:
- name: lint
  image: python:3
  commands:
    - pip install pylint flake8 pylint-flask-sqlalchemy
    - flake8 app
    - pylint app

- name: tests
  image: python:3
  commands:
    - pip install -r requirements.txt
    - pip install -r tests/requirements.txt
    - make tests
