version: '3.3'

services:
  app:
    build: .
    restart: always
    ports:
      - "${PORT}:80"
    depends_on:
      - db
    environment:
      - MAIL_USERNAME
      - MAIL_PASSWORD
      - MAIL_SERVER
      - MAIL_PORT
      - SECRET_KEY
      - DATABASE_URL=mysql://places:places@db/db
    volumes:
      - app_data:/project/instance

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'places'
      MYSQL_PASSWORD: 'places'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  app_data:
