"""Added POIs

Revision ID: 399c64d2ed3f
Revises: 210f4111e8c5
Create Date: 2022-01-07 22:15:04.678678

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '399c64d2ed3f'
down_revision = '210f4111e8c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('POI',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('latitude', app.database.Latitude(), nullable=False),
    sa.Column('longitude', app.database.Longitude(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('POI')
    # ### end Alembic commands ###
