"""Added hiking locations

Revision ID: de73cdceee0e
Revises: 9d571b6c5ae7
Create Date: 2022-03-19 20:38:17.163601

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = 'de73cdceee0e'
down_revision = '9d571b6c5ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hiking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('hiking_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('hiking_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hiking_id'], ['hiking.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('location', sa.Column('hiking_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'location', ['hiking_id'])
    op.create_foreign_key(None, 'location', 'hiking', ['hiking_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_constraint(None, 'location', type_='unique')
    op.drop_column('location', 'hiking_id')
    op.drop_table('hiking_features')
    op.drop_table('hiking')
    # ### end Alembic commands ###
